# Digital Ocean App Platform Configuration for FitForge
# FREE TIER - Static site hosting with Supabase backend

name: fitforge-free
region: nyc

# Static site (FREE tier on Digital Ocean)
static_sites:
  - name: fitforge-frontend
    source_dir: /
    github:
      repo: endersclarity/FitForge
      branch: master
      deploy_on_push: true
    build_command: |
      npm ci &&
      npm run build &&
      npm run check
    output_dir: dist
    
    # Environment variables for build
    envs:
      - key: VITE_SUPABASE_URL
        value: "https://qobrbjpsbwwumzkphlns.supabase.co"
      - key: VITE_SUPABASE_ANON_KEY  
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvYnJianBzYnd3dW16a3BobG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNzU0MzMsImV4cCI6MjA0ODg1MTQzM30.2W_8qaEKNUGdGXKTdJT_WiG7jFKWOBRg9E0JtIHaPRQ"

    # Catchall routing for SPA
    catchall_document: index.html

# Database: Supabase PostgreSQL (Free tier: 500MB database, 2GB bandwidth)
# Authentication: Supabase Auth (Free tier: 50,000 monthly active users)
# Storage: Supabase Storage (Free tier: 1GB storage)

# FREE TIER LIMITS:
# - Static sites: 3 sites, 1GB bandwidth per site
# - Build minutes: 1000 minutes/month  
# - Total cost: $0/month
