# Digital Ocean App Platform Configuration for FitForge
# Production-ready fitness ecosystem deployment

name: fitforge-production
region: nyc

# Environment variables (configure in DO dashboard)
envs:
  - key: NODE_ENV
    value: production
  - key: VITE_SUPABASE_URL
    value: "${SUPABASE_URL}"
    type: SECRET
  - key: VITE_SUPABASE_ANON_KEY
    value: "${SUPABASE_ANON_KEY}"
    type: SECRET

# Frontend build (React + Vite)
static_sites:
  - name: fitforge-frontend
    source_dir: /
    github:
      repo: your-repo/fitforge
      branch: main
    build_command: npm run build
    output_dir: dist
    catchall_document: index.html
    environment_slug: node-js
    
    # Environment variables for build
    envs:
      - key: VITE_SUPABASE_URL
        value: "${SUPABASE_URL}"
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        value: "${SUPABASE_ANON_KEY}"
        type: SECRET

# Backend API (Express.js - if needed for legacy endpoints)
services:
  - name: fitforge-backend
    source_dir: /
    github:
      repo: your-repo/fitforge
      branch: main
    build_command: npm run build:server
    run_command: npm run start:server
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Auto-scaling
    autoscaling:
      min_instance_count: 1
      max_instance_count: 3
      metrics:
        cpu:
          percent: 80
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        value: "${SUPABASE_URL}"
        type: SECRET
      - key: VITE_SUPABASE_ANON_KEY
        value: "${SUPABASE_ANON_KEY}"
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "${SUPABASE_SERVICE_ROLE_KEY}"
        type: SECRET

# Database (using Supabase, but keeping DO Postgres as backup option)
# databases:
#   - name: fitforge-db
#     engine: PG
#     version: "14"
#     size: db-s-1vcpu-1gb
#     num_nodes: 1

# Domain configuration
domains:
  - domain: fitforge.app
    type: PRIMARY
    zone: fitforge.app
  - domain: www.fitforge.app
    type: ALIAS
    zone: fitforge.app

# Features
features:
  - buildpack-stack=ubuntu-22

# Alerts
alerts:
  - rule: CPU_UTILIZATION
    spec:
      disabled: false
      operator: GREATER_THAN
      value: 85
      window: FIVE_MINUTES
  - rule: MEM_UTILIZATION
    spec:
      disabled: false
      operator: GREATER_THAN
      value: 90
      window: FIVE_MINUTES